# Generated by Django 4.0.5 on 2022-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='numCuartos',
            new_name='Ncuartos',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='costoDep',
            new_name='costo',
        ),
        migrations.AlterField(
            model_name='edificio',
            name='direccion',
            field=models.CharField(max_length=80, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre edificio'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], max_length=20),
        ),
    ]
